---
stages:
  - test
  - release

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml
